

export const NANOSKILLS_ACTIONS = {
    LOAD_NANOSKILL: "LOAD_NANOSKILL",
    ADD_NANOSKILL: "ADD_NANOSKILL",
    DELETE_NANOSKILL: "DELETE_NANOSKILL",
    EDIT_NANOSKILL: "EDIT_NANOSKILL",
    ADD_CHILDREN: "ADD_CHILDREN"}